-- CREATE DATABASE instagram;
-- USE instagram;
-- SELECT DATABASE();

-- CREATE TABLE users
-- (
--   id INTEGER AUTO_INCREMENT PRIMARY KEY,
--   username VARCHAR(255) UNIQUE NOT NULL,
--   created_at TIMESTAMP DEFAULT NOW()
-- );
-- DESC users;

-- CREATE TABLE photos
-- (
--   id INT AUTO_INCREMENT PRIMARY KEY,
--   image_url VARCHAR(255) NOT NULL,
--   user_id INT NOT NULL,
--   created_at TIMESTAMP DEFAULT NOW(),
--   FOREIGN KEY(user_id) REFERENCES users(id)
--     ON DELETE CASCADE
-- );
-- DESC photos;

-- CREATE TABLE comments
-- (
--   id INT AUTO_INCREMENT PRIMARY KEY,
--   comment_text VARCHAR(255) NOT NULL,
--   user_id INT NOT NULL,
--   photo_id INT NOT NULL,
--   created_at TIMESTAMP DEFAULT NOW(),
--   FOREIGN KEY(user_id) REFERENCES users(id)
--     ON DELETE CASCADE,
--   FOREIGN KEY(photo_id) REFERENCES photos(id)
--     ON DELETE CASCADE
-- );
-- DESC comments;

-- CREATE TABLE likes
-- (
--   user_id INT NOT NULL,
--   photo_id INT NOT NULL,
--   created_at TIMESTAMP DEFAULT NOW(),
--   FOREIGN KEY(user_id) REFERENCES users(id)
--     ON DELETE CASCADE,
--   FOREIGN KEY(photo_id) REFERENCES photos(id)
--     ON DELETE CASCADE,
--   PRIMARY KEY(user_id, photo_id)
-- );
-- DESC likes;

-- CREATE TABLE follows (
--   follower_id INTEGER NOT NULL,
--   followee_id INTEGER NOT NULL,
--   created_at TIMESTAMP DEFAULT NOW(),
--   FOREIGN KEY(follower_id) REFERENCES users(id),
--   FOREIGN KEY(followee_id) REFERENCES users(id),
--   PRIMARY KEY(follower_id, followee_id)
-- );
-- DESC follows;

-- CREATE TABLE tags
-- ( 
--   id INT AUTO_INCREMENT PRIMARY KEY,
--   tag_name VARCHAR(255) UNIQUE,
--   created_at TIMESTAMP DEFAULT NOW()
-- );
-- DESC tags;

-- CREATE TABLE photo_tags
-- (
--   photo_id INT NOT NULL,
--   tag_id INT NOT NULL,
--   FOREIGN KEY(photo_id) REFERENCES photos(id)
--     ON DELETE CASCADE,
--   FOREIGN KEY(tag_id) REFERENCES tags(id)
--     ON DELETE CASCADE,
--   PRIMARY KEY(photo_id, tag_id)
-- );
-- DESC photo_tags;